INHERIT: mkdocs_shared.yml

site_name: MkDocstrings
site_description: A MkDocstrings page created by MkNodes
repo_url: "https://github.com/mkdocstrings/mkdocstrings/"
site_url: https://phil65.github.io/mknodes/mkdocstrings/
plugins:
- mknodes:
    repo_path: https://github.com/mkdocstrings/mkdocstrings.git
    clone_depth: 100
    build_fn: mknodes.navs.mkemptywebsite:MkEmptyWebsite.for_project
    kwargs:
      static_pages:
        Development:
          - Changelog: "{{ mk.MkChangelog() }}"
          - Code of conduct: "{{ mk.MkCodeOfConduct() }}"
          - Commit conventions: "{{ mk.MkCommitConventions() }}"
          - Pull requests: "{{ mk.MkPullRequestGuidelines() }}"
          - Development environment: "{{ mk.MkDevEnvSetup() }}"
          - Tools: "{{ mk.MkDevTools() }}"
          - Dependencies: "{{ mk.MkDependencyTable() }}"
          - Plugin flow: "{{ mk.MkPluginFlow() }}"
          - License: "{{ mk.MkLicense() }}"
